---
# Install docker-machine
- name: Get version
  command: uname -s
  register: os_kernel_name

- name: Get version
  command: uname -m
  register: os_machine

- name: Get docker-machine
  get_url:
    url={{ machine_base_url }}/docker-machine-{{ os_kernel_name.stdout }}-{{ os_machine.stdout }}
    dest={{ machine_target_path }}

- name: Set permission
  file: path={{ machine_target_path }} mode=755

