# See also
# https://docs.docker.com/engine/installation/linux/centos/
# http://qiita.com/gillax/items/6f864e7c21c6a3e4173b
- name: Update yum repo
  yum: name=* update_cache=yes

- name: Put repofile
  copy: src=docker.repo.{{ ansible_distribution_major_version }}
        dest=/etc/yum.repos.d/docker.repo

- name: Install docker-engine
  yum: name=docker-engine update_cache=yes

- name: Start the docker daemon
  service: name=docker state=started
