# https://hub.docker.com/r/couchbase/server/
# http://developer.couchbase.com/documentation/server/current/install/deploy-with-docker-hub.html
# http://blog.couchbase.com/2016/february/couchbase-docker-container
version: '2'

services:
  database:
    image: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    ulimits:
      nofile: 40960
      core: 100000000
      memlock: 100000000

