version: '2'

services:
  openjdk8:
    build:
      context: ./openjdk8
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        no_proxy: ${NO_PROXY}
    image: local/openjdk8

  tomcat7:
    build:
      context: ./tomcat7
    image: local/tomcat7
    depends_on:
      - openjdk8

  gitbucket:
    build:
      context: ./gitbucket
    image: local/gitbucket
    ports:
      - "8080:8080"
    depends_on:
      - tomcat7
    volumes:
      - ./gitbucket/home:/root/.gitbucket

# jenkins:
#   build:
#     context: ./jenkins
#   image: local/jenkins
#   ports:
#     - "49001:8080"
#   volumes:
#     - ./jenkins/home:/var/jenkins_home
