---
# Install docker on Ubuntu
# https://docs.docker.com/engine/installation/linux/ubuntulinux/
- hosts: local
  become: yes
  become_user: root
  roles:
    - { role: docker-engine-Debian,
        when: ansible_os_family == "Debian" }
    - { role: docker-engine-RedHat,
        when: ansible_os_family == "RedHat" }
    - docker-compose
    - docker-machine
